### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by deneuxa** [basecamp/mail_view#33]
Getting this error.
I put this  in my model mail_view.rb of course...
     # -_\- encoding : utf-8 -_-

**Comment by dplummer** [comment]
Did you ever figure this out? I'm running into the same error. It's being caused by some I18n translations in my mailer views, it appears.

```
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/mail_view-1.0.3/lib/mail_view/email.html.erb:84:in `block in singletonclass'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/mail_view-1.0.3/lib/mail_view/email.html.erb:65529:in `instance_eval'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/mail_view-1.0.3/lib/mail_view/email.html.erb:65529:in `singletonclass'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/mail_view-1.0.3/lib/mail_view/email.html.erb:65527:in `__tilt_17971800'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/tilt-1.3.6/lib/tilt/template.rb:144:in `call'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/tilt-1.3.6/lib/tilt/template.rb:144:in `evaluate'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/tilt-1.3.6/lib/tilt/template.rb:77:in `render'
/home/dplummer/.rvm/gems/ruby-1.9.3-p392/gems/mail_view-1.0.3/lib/mail_view.rb:89:in `render_mail'
```

**Comment by the-architect** [comment]
Same issue here. Did you solve it?

**Comment by deneuxa** [comment]
nope, I switched to mailcatcher

**Comment by the-architect** [comment]
too bad :(

**Comment by the-architect** [comment]
master works for me.
