### ISSUE TITLE
A copy of MailPreview has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by bbuchalter** [basecamp/mail_view#37]
Using Rails 4.0.0.beta1 and Ruby 2.0.0. While using mail_view, if I encounter an error, fix the error and reload, I get the error in $subject. Restarting webrick resolves the issue.

Full backtrace:

```
activesupport (4.0.0.beta1) lib/active_support/dependencies.rb:445:in `load_missing_constant'
activesupport (4.0.0.beta1) lib/active_support/dependencies.rb:183:in `const_missing'
app/mailers/mail_preview.rb:3:in `week_parent_report'
/home/brianb/.rvm/gems/ruby-2.0.0-p0/bundler/gems/mail_view-2e2b00897cb7/lib/mail_view.rb:38:in `call'
/home/brianb/.rvm/gems/ruby-2.0.0-p0/bundler/gems/mail_view-2e2b00897cb7/lib/mail_view.rb:19:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/journey/router.rb:69:in `block in call'
actionpack (4.0.0.beta1) lib/action_dispatch/journey/router.rb:57:in `each'
actionpack (4.0.0.beta1) lib/action_dispatch/journey/router.rb:57:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/routing/route_set.rb:651:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/cookies.rb:452:in `call'
dragonfly (0.9.14) lib/dragonfly/cookie_monster.rb:9:in `call'
activerecord (4.0.0.beta1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0.beta1) lib/active_record/connection_adapters/abstract/connection_pool.rb:632:in `call'
activerecord (4.0.0.beta1) lib/active_record/migration.rb:348:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0.beta1) lib/active_support/callbacks.rb:373:in `_run__3326616950422825945__call__callbacks'
activesupport (4.0.0.beta1) lib/active_support/callbacks.rb:78:in `run_callbacks'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.0.beta1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.0.beta1) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0.beta1) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0.beta1) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0.beta1) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0.beta1) lib/rails/rack/logger.rb:21:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.0.beta1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0.beta1) lib/action_dispatch/middleware/static.rb:64:in `call'
dragonfly (0.9.14) lib/dragonfly/middleware.rb:13:in `call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
railties (4.0.0.beta1) lib/rails/engine.rb:510:in `call'
railties (4.0.0.beta1) lib/rails/application.rb:96:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/brianb/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/home/brianb/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/home/brianb/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

```
# Gemfile.lock
GIT
  remote: git://github.com/37signals/mail_view.git
  revision: 2e2b00897cb79b1a6924240b43a7521915efe215
  specs:
    mail_view (1.0.1)
      tilt

GIT
  remote: git://github.com/vmg/rinku.git
  revision: 49cf3588bb7ce9d4626e67b70a5f8cb90308b7c2
  specs:
    rinku (1.7.2)

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.0.0.beta1)
      actionpack (= 4.0.0.beta1)
      mail (~> 2.5.3)
    actionpack (4.0.0.beta1)
      activesupport (= 4.0.0.beta1)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.0.beta1)
      activesupport (= 4.0.0.beta1)
      builder (~> 3.1.0)
    activerecord (4.0.0.beta1)
      activemodel (= 4.0.0.beta1)
      activerecord-deprecated_finders (~> 0.0.3)
      activesupport (= 4.0.0.beta1)
      arel (~> 4.0.0.beta1)
    activerecord-deprecated_finders (0.0.3)
    activesupport (4.0.0.beta1)
      i18n (~> 0.6.2)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.33)
    arel (4.0.0.beta2)
    atomic (1.0.1)
    builder (3.1.4)
    coffee-rails (4.0.0.beta1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0.beta, < 5.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.2)
    columnize (0.3.6)
    commonjs (0.2.6)
    debugger (1.5.0)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.2.0)
      debugger-ruby_core_source (~> 1.2.0)
    debugger-linecache (1.2.0)
    debugger-ruby_core_source (1.2.0)
    dragonfly (0.9.14)
      multi_json (~> 1.0)
      rack
    erubis (2.7.0)
    execjs (1.4.0)
      multi_json (~> 1.0)
    hike (1.2.1)
    i18n (0.6.4)
    jbuilder (1.0.2)
      activesupport (>= 3.0.0)
    jquery-rails (2.2.1)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.7.7)
    less (2.3.1)
      commonjs (~> 0.2.6)
    less-rails (2.3.2)
      actionpack (>= 3.1)
      less (~> 2.3.1)
    libv8 (3.11.8.17)
    mail (2.5.3)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.21)
    minitest (4.7.0)
    multi_json (1.7.2)
    polyglot (0.3.3)
    rack (1.5.2)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.0.beta1)
      actionmailer (= 4.0.0.beta1)
      actionpack (= 4.0.0.beta1)
      activerecord (= 4.0.0.beta1)
      activesupport (= 4.0.0.beta1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.0.beta1)
      sprockets-rails (~> 2.0.0.rc3)
    railties (4.0.0.beta1)
      actionpack (= 4.0.0.beta1)
      activesupport (= 4.0.0.beta1)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.17.0, < 2.0)
    rake (10.0.4)
    rdoc (3.12.2)
      json (~> 1.4)
    ref (1.0.4)
    sass (3.2.7)
    sass-rails (4.0.0.beta1)
      railties (>= 4.0.0.beta, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0.rc0)
      tilt (~> 1.3)
    sprockets (2.9.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.0.rc3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    sqlite3 (1.3.7)
    therubyracer (0.11.4)
      libv8 (~> 3.11.8.12)
      ref
    thor (0.18.0)
    thread_safe (0.1.0)
      atomic
    tilt (1.3.6)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    twitter-bootstrap-rails (2.2.6)
      actionpack (>= 3.1)
      execjs
      railties (>= 3.1)
    tzinfo (0.3.37)
    uglifier (1.3.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  coffee-rails (~> 4.0.0.beta1)
  debugger
  dragonfly
  jbuilder (~> 1.0.1)
  jquery-rails
  less-rails
  mail_view!
  rack-cache
  rails (= 4.0.0.beta1)
  rinku!
  sass-rails (~> 4.0.0.beta1)
  sqlite3
  therubyracer
  twitter-bootstrap-rails
  uglifier (>= 1.0.3)
```

**Comment by trevorturk** [comment]
I've been trying to debug this issue, but I'm still not 100% sure what's up. I think there may be a bug in Rails causing this, so I opened an issue about it here: https://github.com/rails/rails/issues/10685

**Comment by trevorturk** [comment]
Fixed in https://github.com/rails/rails/issues/10685 :tada:
